import type { ComplianceControl, ComplianceFramework } from "@/lib/compliance/types";

/** Representative SOC 2 Trust Services Criteria + ISO 27001:2022 annex A controls used for mapping. */
export const COMPLIANCE_CONTROLS: ComplianceControl[] = [
  { id: "soc2:CC1.2", framework: "soc2", ref: "CC1.2", title: "Board oversight of internal control", domain: "Control environment" },
  { id: "soc2:CC1.4", framework: "soc2", ref: "CC1.4", title: "Commitment to competence", domain: "Control environment" },
  { id: "soc2:CC5.3", framework: "soc2", ref: "CC5.3", title: "Policies and procedures", domain: "Control activities" },
  { id: "soc2:CC6.1", framework: "soc2", ref: "CC6.1", title: "Logical access security", domain: "Logical access" },
  { id: "soc2:CC6.6", framework: "soc2", ref: "CC6.6", title: "System boundaries and credentials", domain: "Logical access" },
  { id: "soc2:CC7.2", framework: "soc2", ref: "CC7.2", title: "Monitor anomalies and security events", domain: "Monitoring" },
  { id: "soc2:CC7.3", framework: "soc2", ref: "CC7.3", title: "Evaluate and respond to security events", domain: "Monitoring" },
  { id: "soc2:CC7.4", framework: "soc2", ref: "CC7.4", title: "Incident response program", domain: "Monitoring" },
  { id: "soc2:CC8.1", framework: "soc2", ref: "CC8.1", title: "Authorize and implement changes", domain: "Change management" },
  { id: "iso:A.5.15", framework: "iso27001", ref: "A.5.15", title: "Access control", domain: "Organizational" },
  { id: "iso:A.5.23", framework: "iso27001", ref: "A.5.23", title: "Information security for cloud services", domain: "Organizational" },
  { id: "iso:A.8.2", framework: "iso27001", ref: "A.8.2", title: "Privileged access rights", domain: "Technological" },
  { id: "iso:A.8.9", framework: "iso27001", ref: "A.8.9", title: "Configuration management", domain: "Technological" },
  { id: "iso:A.8.16", framework: "iso27001", ref: "A.8.16", title: "Monitoring activities", domain: "Technological" },
  { id: "iso:A.8.25", framework: "iso27001", ref: "A.8.25", title: "Secure development lifecycle", domain: "Technological" },
  { id: "iso:A.5.24", framework: "iso27001", ref: "A.5.24", title: "Information security incident management", domain: "Organizational" },
  { id: "pcidss:1.2.1", framework: "pcidss", ref: "1.2.1", title: "Network security controls defined and implemented", domain: "Requirement 1" },
  { id: "pcidss:2.2.2", framework: "pcidss", ref: "2.2.2", title: "System components configured securely", domain: "Requirement 2" },
  { id: "pcidss:3.2.1", framework: "pcidss", ref: "3.2.1", title: "Account data storage minimized", domain: "Requirement 3" },
  { id: "pcidss:4.2.1", framework: "pcidss", ref: "4.2.1", title: "Strong cryptography for transmission of cardholder data", domain: "Requirement 4" },
  { id: "pcidss:5.3.1", framework: "pcidss", ref: "5.3.1", title: "Anti-malware mechanisms active and monitored", domain: "Requirement 5" },
  { id: "pcidss:6.3.1", framework: "pcidss", ref: "6.3.1", title: "Security vulnerabilities identified and addressed", domain: "Requirement 6" },
  { id: "pcidss:7.2.1", framework: "pcidss", ref: "7.2.1", title: "Access restricted by least privilege", domain: "Requirement 7" },
  { id: "pcidss:8.3.1", framework: "pcidss", ref: "8.3.1", title: "Multi-factor authentication for remote access", domain: "Requirement 8" },
  { id: "pcidss:10.2.1", framework: "pcidss", ref: "10.2.1", title: "Audit logs implemented and protected", domain: "Requirement 10" },
  { id: "pcidss:11.5.1", framework: "pcidss", ref: "11.5.1", title: "Intrusion detection and prevention", domain: "Requirement 11" },
  { id: "pcidss:12.3.1", framework: "pcidss", ref: "12.3.1", title: "Targeted risk analysis for PCI scope", domain: "Requirement 12" },
  { id: "hipaa:164.308a1", framework: "hipaa", ref: "164.308(a)(1)", title: "Security management process", domain: "Administrative" },
  { id: "hipaa:164.308a3", framework: "hipaa", ref: "164.308(a)(3)", title: "Workforce security", domain: "Administrative" },
  { id: "hipaa:164.308a4", framework: "hipaa", ref: "164.308(a)(4)", title: "Information access management", domain: "Administrative" },
  { id: "hipaa:164.308a6", framework: "hipaa", ref: "164.308(a)(6)", title: "Security incident procedures", domain: "Administrative" },
  { id: "hipaa:164.308b1", framework: "hipaa", ref: "164.308(b)(1)", title: "Business associate agreements (BAA)", domain: "Administrative" },
  { id: "hipaa:164.310a1", framework: "hipaa", ref: "164.310(a)(1)", title: "Facility access controls", domain: "Physical" },
  { id: "hipaa:164.312a1", framework: "hipaa", ref: "164.312(a)(1)", title: "Access control", domain: "Technical" },
  { id: "hipaa:164.312b", framework: "hipaa", ref: "164.312(b)", title: "Audit controls", domain: "Technical" },
  { id: "hipaa:164.312c1", framework: "hipaa", ref: "164.312(c)(1)", title: "Integrity controls", domain: "Technical" },
  { id: "hipaa:164.312d", framework: "hipaa", ref: "164.312(d)", title: "Person or entity authentication", domain: "Technical" },
  { id: "hipaa:164.312e1", framework: "hipaa", ref: "164.312(e)(1)", title: "Transmission security", domain: "Technical" },
  { id: "nist_csf:GV.OC-01", framework: "nist_csf", ref: "GV.OC-01", title: "Organizational cybersecurity risk strategy", domain: "Govern" },
  { id: "nist_csf:GV.PO-01", framework: "nist_csf", ref: "GV.PO-01", title: "Cybersecurity policy established and communicated", domain: "Govern" },
  { id: "nist_csf:ID.AM-01", framework: "nist_csf", ref: "ID.AM-01", title: "Hardware assets inventoried", domain: "Identify" },
  { id: "nist_csf:ID.RA-01", framework: "nist_csf", ref: "ID.RA-01", title: "Vulnerabilities identified and documented", domain: "Identify" },
  { id: "nist_csf:PR.AA-01", framework: "nist_csf", ref: "PR.AA-01", title: "Identities and credentials managed", domain: "Protect" },
  { id: "nist_csf:PR.DS-01", framework: "nist_csf", ref: "PR.DS-01", title: "Data-at-rest protected", domain: "Protect" },
  { id: "nist_csf:DE.CM-01", framework: "nist_csf", ref: "DE.CM-01", title: "Networks and systems monitored", domain: "Detect" },
  { id: "nist_csf:DE.AE-01", framework: "nist_csf", ref: "DE.AE-01", title: "Anomalies and events analyzed", domain: "Detect" },
  { id: "nist_csf:RS.MA-01", framework: "nist_csf", ref: "RS.MA-01", title: "Incidents managed", domain: "Respond" },
  { id: "nist_csf:RS.AN-01", framework: "nist_csf", ref: "RS.AN-01", title: "Incidents analyzed for impact", domain: "Respond" },
  { id: "nist_csf:RC.RP-01", framework: "nist_csf", ref: "RC.RP-01", title: "Recovery plan executed", domain: "Recover" },
  { id: "nist_csf:RC.CO-01", framework: "nist_csf", ref: "RC.CO-01", title: "Recovery activities communicated", domain: "Recover" },
  { id: "cis_v8:1.1", framework: "cis_v8", ref: "1.1", title: "Establish enterprise asset inventory", domain: "IG1" },
  { id: "cis_v8:2.1", framework: "cis_v8", ref: "2.1", title: "Establish software inventory", domain: "IG1" },
  { id: "cis_v8:4.1", framework: "cis_v8", ref: "4.1", title: "Establish secure configuration process", domain: "IG1" },
  { id: "cis_v8:6.1", framework: "cis_v8", ref: "6.1", title: "Establish access granting process", domain: "IG1" },
  { id: "cis_v8:5.2", framework: "cis_v8", ref: "5.2", title: "Use unique passwords", domain: "IG2" },
  { id: "cis_v8:6.3", framework: "cis_v8", ref: "6.3", title: "Enable audit log collection", domain: "IG2" },
  { id: "cis_v8:7.1", framework: "cis_v8", ref: "7.1", title: "Establish vulnerability management process", domain: "IG2" },
  { id: "cis_v8:8.2", framework: "cis_v8", ref: "8.2", title: "Collect audit logs", domain: "IG2" },
  { id: "cis_v8:11.2", framework: "cis_v8", ref: "11.2", title: "Remediate vulnerabilities", domain: "IG3" },
  { id: "cis_v8:12.8", framework: "cis_v8", ref: "12.8", title: "Collect service provider logs", domain: "IG3" },
  { id: "cis_v8:13.2", framework: "cis_v8", ref: "13.2", title: "Deploy host-based intrusion detection", domain: "IG3" },
  { id: "cis_v8:17.1", framework: "cis_v8", ref: "17.1", title: "Designate incident management personnel", domain: "IG3" },
  { id: "cmmc_l2:3.1.1", framework: "cmmc_l2", ref: "3.1.1", title: "Limit system access to authorized users", domain: "AC" },
  { id: "cmmc_l2:3.1.2", framework: "cmmc_l2", ref: "3.1.2", title: "Limit access to authorized transactions and functions", domain: "AC" },
  { id: "cmmc_l2:3.5.2", framework: "cmmc_l2", ref: "3.5.2", title: "Authenticate identities before allowing access", domain: "IA" },
  { id: "cmmc_l2:3.3.1", framework: "cmmc_l2", ref: "3.3.1", title: "Create and retain system audit logs", domain: "AU" },
  { id: "cmmc_l2:3.3.2", framework: "cmmc_l2", ref: "3.3.2", title: "Ensure audit logs uniquely trace users", domain: "AU" },
  { id: "cmmc_l2:3.4.1", framework: "cmmc_l2", ref: "3.4.1", title: "Establish and maintain configuration baselines", domain: "CM" },
  { id: "cmmc_l2:3.4.2", framework: "cmmc_l2", ref: "3.4.2", title: "Establish and enforce security configuration settings", domain: "CM" },
  { id: "cmmc_l2:3.6.1", framework: "cmmc_l2", ref: "3.6.1", title: "Establish an operational incident-handling capability", domain: "IR" },
  { id: "cmmc_l2:3.6.2", framework: "cmmc_l2", ref: "3.6.2", title: "Track, document, and report incidents", domain: "IR" },
  { id: "cmmc_l2:3.11.2", framework: "cmmc_l2", ref: "3.11.2", title: "Scan for vulnerabilities and remediate", domain: "RA" },
  { id: "cmmc_l2:3.13.1", framework: "cmmc_l2", ref: "3.13.1", title: "Monitor communications at system boundaries", domain: "SC" },
  { id: "cmmc_l2:3.14.2", framework: "cmmc_l2", ref: "3.14.2", title: "Provide protection from malicious code", domain: "SI" },
  { id: "gdpr_art32:32-a1", framework: "gdpr_art32", ref: "32-a1", title: "Pseudonymisation where appropriate", domain: "Encryption" },
  { id: "gdpr_art32:32-a2", framework: "gdpr_art32", ref: "32-a2", title: "Encryption of personal data in transit and at rest", domain: "Encryption" },
  { id: "gdpr_art32:32-b1", framework: "gdpr_art32", ref: "32-b1", title: "Ongoing confidentiality of processing", domain: "Confidentiality" },
  { id: "gdpr_art32:32-b2", framework: "gdpr_art32", ref: "32-b2", title: "Access controls limiting personal data access", domain: "Confidentiality" },
  { id: "gdpr_art32:32-i1", framework: "gdpr_art32", ref: "32-i1", title: "Integrity of processing systems and services", domain: "Integrity" },
  { id: "gdpr_art32:32-i2", framework: "gdpr_art32", ref: "32-i2", title: "Change control for systems processing personal data", domain: "Integrity" },
  { id: "gdpr_art32:32-v1", framework: "gdpr_art32", ref: "32-v1", title: "Ongoing availability of processing systems", domain: "Availability" },
  { id: "gdpr_art32:32-v2", framework: "gdpr_art32", ref: "32-v2", title: "Capacity and performance monitoring", domain: "Availability" },
  { id: "gdpr_art32:32-r1", framework: "gdpr_art32", ref: "32-r1", title: "Resilience of processing systems and services", domain: "Resilience" },
  { id: "gdpr_art32:32-r2", framework: "gdpr_art32", ref: "32-r2", title: "Timely restore of availability and access to personal data", domain: "Resilience" },
  { id: "gdpr_art32:32-d1", framework: "gdpr_art32", ref: "32-d1", title: "Regular testing of security measures", domain: "Assurance" },
  { id: "gdpr_art32:32-d2", framework: "gdpr_art32", ref: "32-d2", title: "Evaluation of technical measure effectiveness", domain: "Assurance" },
];

const BY_ID = new Map(COMPLIANCE_CONTROLS.map((c) => [c.id, c]));

export function getComplianceControl(id: string): ComplianceControl | undefined {
  return BY_ID.get(id);
}

export function listControlsByFramework(framework: ComplianceFramework | "all"): ComplianceControl[] {
  if (framework === "all") return COMPLIANCE_CONTROLS;
  return COMPLIANCE_CONTROLS.filter((c) => c.framework === framework);
}
