/** Shared console navigation — hub + module shortcuts. */
export const CONSOLE_MODULES = [
  {
    href: "/hub",
    label: "Platform",
    description: "Home",
    icon: "◆",
    live: true,
  },
  {
    href: "/overview",
    label: "Overview",
    description: "Command center",
    icon: "⌁",
    live: true,
  },
  {
    href: "/copilot",
    label: "Copilot",
    description: "AI triage",
    icon: "◎",
    live: true,
  },
  {
    href: "/incidents",
    label: "Incidents",
    description: "Track & resolve",
    icon: "▣",
    live: true,
  },
  {
    href: "/automations",
    label: "Automations",
    description: "Playbooks",
    icon: "⎔",
    live: true,
  },
  {
    href: "/runbooks",
    label: "Runbooks",
    description: "Procedures",
    icon: "📋",
    live: true,
  },
  {
    href: "/approvals",
    label: "Approvals",
    description: "Human gates",
    icon: "✓",
    live: true,
  },
  {
    href: "/audit",
    label: "Audit",
    description: "Trail",
    icon: "≡",
    live: true,
  },
  {
    href: "/settings",
    label: "Settings",
    description: "Hub",
    icon: "⚙",
    live: true,
  },
  {
    href: "/settings/billing",
    label: "Billing",
    description: "Plan",
    icon: "$",
    live: true,
  },
  {
    href: "/settings/api-keys",
    label: "API keys",
    description: "Integrate",
    icon: "⦿",
    live: true,
  },
  {
    href: "/settings/connectors",
    label: "Connectors",
    description: "Services",
    icon: "◇",
    live: true,
  },
] as const;
