import type { ConsoleModuleIconName } from "@/components/icons/AppIcon";

/** Shared console navigation — hub + module shortcuts. */
export const CONSOLE_MODULES: readonly {
  href: string;
  label: string;
  description: string;
  icon: ConsoleModuleIconName;
  live: boolean;
}[] = [
  {
    href: "/hub",
    label: "Platform",
    description: "Home",
    icon: "layoutDashboard",
    live: true,
  },
  {
    href: "/vision",
    label: "Vision",
    description: "Roadmap",
    icon: "telescope",
    live: true,
  },
  {
    href: "/overview",
    label: "Overview",
    description: "Command center",
    icon: "gauge",
    live: true,
  },
  {
    href: "/copilot",
    label: "Copilot",
    description: "AI triage",
    icon: "bot",
    live: true,
  },
  {
    href: "/incidents",
    label: "Incidents",
    description: "Track & resolve",
    icon: "alertTriangle",
    live: true,
  },
  {
    href: "/services",
    label: "Services",
    description: "Catalog & alerts",
    icon: "server",
    live: true,
  },
  {
    href: "/assets/certificates",
    label: "Certificates",
    description: "Expiry inventory",
    icon: "shieldCheck",
    live: true,
  },
  {
    href: "/assets/secrets",
    label: "Secrets",
    description: "Rotation posture",
    icon: "keyRound",
    live: true,
  },
  {
    href: "/assets/network",
    label: "Network",
    description: "Device inventory",
    icon: "server",
    live: true,
  },
  {
    href: "/assets/vulnerabilities",
    label: "Vulnerabilities",
    description: "Scanner findings",
    icon: "alertTriangle",
    live: true,
  },
  {
    href: "/assets/attack-paths",
    label: "Attack paths",
    description: "Path simulation",
    icon: "alertTriangle",
    live: true,
  },
  {
    href: "/resilience/backups",
    label: "Backups",
    description: "DR readiness",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/changes",
    label: "Changes",
    description: "Calendar",
    icon: "workflow",
    live: true,
  },
  {
    href: "/governance/access",
    label: "Access",
    description: "MFA posture",
    icon: "shieldCheck",
    live: true,
  },
  {
    href: "/governance/compliance/evidence-request-sla",
    label: "Request SLA",
    description: "Evidence fulfillment SLAs",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/evidence-requests",
    label: "Evidence requests",
    description: "Assessor document workflow",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/exception-register",
    label: "Exception register",
    description: "Policy & control exceptions",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/control-ownership",
    label: "Ownership matrix",
    description: "RACI control owners",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/attestation-renewal",
    label: "Renewal calendar",
    description: "Attestation renewal waves",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/committee-meeting-pack",
    label: "Committee pack",
    description: "Quarterly review ZIP",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/control-health-scorecard",
    label: "Health scorecard",
    description: "Leadership control health",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/posture-score",
    label: "Posture score",
    description: "Unified GRC score 0–100",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/program",
    label: "Program dashboard",
    description: "Executive rollup",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/executive-summary",
    label: "Executive summary",
    description: "Board-ready GRC printout",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/calendar",
    label: "GRC calendar",
    description: "Audit season planner",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/obligation-ics",
    label: "Obligation ICS",
    description: "Calendar app export",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/runbooks",
    label: "Gap runbooks",
    description: "Remediation tracking",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/type-ii",
    label: "SOC 2 Type II",
    description: "Control monitoring",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/iso-assessment",
    label: "ISO 27001",
    description: "Annex A assessment",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/pci-dss",
    label: "PCI DSS",
    description: "Cardholder controls",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/hipaa",
    label: "HIPAA",
    description: "Healthcare safeguards",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/nist-csf",
    label: "NIST CSF",
    description: "Framework alignment",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/cis-v8",
    label: "CIS Controls v8",
    description: "IG safeguard pack",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/cmmc-l2",
    label: "CMMC Level 2",
    description: "800-171 overlay",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/gdpr-art32",
    label: "GDPR Art. 32",
    description: "Security of processing",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/crosswalk",
    label: "SOC 2 / ISO crosswalk",
    description: "Mapping matrix export",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/workbook",
    label: "Assessor workbook",
    description: "Unified ZIP export",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/mapping-digest",
    label: "Mapping digest",
    description: "Catalog & crosswalk alerts",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/digest",
    label: "Compliance digest",
    description: "Weekly GRC webhooks",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/sla-reminders",
    label: "SLA reminders",
    description: "Email & Slack nudges",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/fedramp-poam",
    label: "FedRAMP POA&M",
    description: "NIST 800-53 POA&M CSV",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/evidence-freshness",
    label: "Evidence freshness",
    description: "Stale control queue",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/baseline-comparison",
    label: "Baseline comparison",
    description: "All-framework readiness",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/benchmarking",
    label: "Control benchmarking",
    description: "Industry percentile bands",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/policy-drift",
    label: "Policy drift",
    description: "Guardrail vs gap analysis",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/control-graph",
    label: "Control graph",
    description: "Cross-framework dependencies",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/regulatory-impact",
    label: "Regulatory impact",
    description: "Change scenario simulator",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/evidence-lineage",
    label: "Evidence lineage",
    description: "Audit → bundle → workbook",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/testing-evidence-linker",
    label: "Test evidence linker",
    description: "Dry-runs ↔ bundles",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/testing-schedules",
    label: "Testing schedules",
    description: "Recurring evidence windows",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/scope-boundary",
    label: "Scope boundary",
    description: "Systems → control packs",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/kpi-trends",
    label: "KPI trends",
    description: "Readiness & remediation velocity",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/risk-heatmap",
    label: "Risk heatmap",
    description: "Framework & vendor concentration",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/obligation-heatmap",
    label: "Obligation heatmap",
    description: "Open obligations by framework",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/obligation-crossover",
    label: "Obligation crossover",
    description: "Multi-framework reuse clusters",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/obligation-consolidation",
    label: "Obligation consolidation",
    description: "Crossover evidence playbook",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/obligation-forecast",
    label: "Obligation forecast",
    description: "Board timeline density",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/obligation-whatif",
    label: "Obligation what-if",
    description: "Forecast stress scenarios",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/committee-capacity-budget",
    label: "Capacity budget",
    description: "Owner-hours vs forecast peaks",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/obligation-load-balancing",
    label: "Load balancing",
    description: "Peak-week owner rebalance",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/peak-week-staffing-digest",
    label: "Staffing digest",
    description: "Peak-week capacity + load alert",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/staffing-actions",
    label: "Staffing actions",
    description: "Track relief through completion",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/staffing-action-reminders",
    label: "Overdue reminders",
    description: "Nudge open actions past peak week",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/staffing-completion-rollup",
    label: "Completion rollup",
    description: "Printable staffing archive",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/staffing-sla-breach-digest",
    label: "SLA breach digest",
    description: "Post-peak completion SLA alerts",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/cross-staffing-committee-escalation",
    label: "Committee escalation",
    description: "Escalate after rollup email",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/staffing-digest-auto-chain",
    label: "Digest auto-chain",
    description: "Rollup → SLA → escalation cron",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/committee-digest",
    label: "Committee digest",
    description: "Quarterly obligation email",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/obligation-rollup",
    label: "Executive rollup",
    description: "Printable board PDF packet",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/obligation-density-alerts",
    label: "Density alerts",
    description: "Weekly density Slack and email",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/obligation-density-trend-history",
    label: "Density trends",
    description: "Trailing-quarter density chart",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/assessor-api",
    label: "Assessor API",
    description: "Read-only export tokens",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/inherited-control-gaps",
    label: "Vendor control gaps",
    description: "Inherited control coverage",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/third-party-risk",
    label: "Third-party risk",
    description: "Vendor register",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance/attestations",
    label: "Attestations",
    description: "Control sign-off",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/compliance",
    label: "Compliance",
    description: "SOC 2 / ISO mapping",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/governance/policies",
    label: "Policy review",
    description: "DI suggestions",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/automations",
    label: "Automations",
    description: "Playbooks",
    icon: "workflow",
    live: true,
  },
  {
    href: "/runbooks",
    label: "Runbooks",
    description: "Procedures",
    icon: "bookOpen",
    live: true,
  },
  {
    href: "/approvals",
    label: "Approvals",
    description: "Human gates",
    icon: "shieldCheck",
    live: true,
  },
  {
    href: "/audit",
    label: "Audit",
    description: "Compliance log",
    icon: "scrollText",
    live: true,
  },
  {
    href: "/settings",
    label: "Settings",
    description: "Hub",
    icon: "settings",
    live: true,
  },
  {
    href: "/settings/members",
    label: "Members",
    description: "Org RBAC",
    icon: "shieldCheck",
    live: true,
  },
  {
    href: "/settings/billing",
    label: "Billing",
    description: "Plan",
    icon: "creditCard",
    live: true,
  },
  {
    href: "/settings/api-keys",
    label: "API keys",
    description: "Integrate",
    icon: "keyRound",
    live: true,
  },
  {
    href: "/settings/connectors",
    label: "Connectors",
    description: "Services",
    icon: "plug2",
    live: true,
  },
] as const;
